//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token đã hết hạn.
        /// </summary>
        internal static string ExpiredToken {
            get {
                return ResourceManager.GetString("ExpiredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu báo cáo.
        /// </summary>
        internal static string QuyenBC_BAOCAO {
            get {
                return ResourceManager.GetString("QuyenBC_BAOCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo tổng hợp.
        /// </summary>
        internal static string QuyenBC_TONGHOP {
            get {
                return ResourceManager.GetString("QuyenBC_TONGHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình danh mục.
        /// </summary>
        internal static string QuyenDM_DANHMUC {
            get {
                return ResourceManager.GetString("QuyenDM_DANHMUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        internal static string QuyenDM_DANHMUC_ITEM {
            get {
                return ResourceManager.GetString("QuyenDM_DANHMUC_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình từ điển.
        /// </summary>
        internal static string QuyenDM_TUDIEN {
            get {
                return ResourceManager.GetString("QuyenDM_TUDIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình từ vựng.
        /// </summary>
        internal static string QuyenDM_TUDIEN_ITEM {
            get {
                return ResourceManager.GetString("QuyenDM_TUDIEN_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao lưu phục hồi.
        /// </summary>
        internal static string QuyenHT_BACKUP {
            get {
                return ResourceManager.GetString("QuyenHT_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình hệ thống.
        /// </summary>
        internal static string QuyenHT_CAUHINH {
            get {
                return ResourceManager.GetString("QuyenHT_CAUHINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình hệ thống đơn vị.
        /// </summary>
        internal static string QuyenHT_CAUHINHDV {
            get {
                return ResourceManager.GetString("QuyenHT_CAUHINHDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đơn vị.
        /// </summary>
        internal static string QuyenHT_CHONDV {
            get {
                return ResourceManager.GetString("QuyenHT_CHONDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu trữ tài liệu, báo cáo.
        /// </summary>
        internal static string QuyenHT_FILE {
            get {
                return ResourceManager.GetString("QuyenHT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử hệ thống.
        /// </summary>
        internal static string QuyenHT_LICHSU {
            get {
                return ResourceManager.GetString("QuyenHT_LICHSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu hệ thống.
        /// </summary>
        internal static string QuyenHT_MENU {
            get {
                return ResourceManager.GetString("QuyenHT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết menu.
        /// </summary>
        internal static string QuyenHT_MENUITEM {
            get {
                return ResourceManager.GetString("QuyenHT_MENUITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        internal static string QuyenHT_NGUOIDUNG {
            get {
                return ResourceManager.GetString("QuyenHT_NGUOIDUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm quyền.
        /// </summary>
        internal static string QuyenHT_NHOMQUYEN {
            get {
                return ResourceManager.GetString("QuyenHT_NHOMQUYEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp tin.
        /// </summary>
        internal static string QuyenHT_TEP {
            get {
                return ResourceManager.GetString("QuyenHT_TEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo hệ thống.
        /// </summary>
        internal static string QuyenHT_THONGBAO {
            get {
                return ResourceManager.GetString("QuyenHT_THONGBAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nhắn.
        /// </summary>
        internal static string QuyenHT_TINNHAN {
            get {
                return ResourceManager.GetString("QuyenHT_TINNHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý bàn giao.
        /// </summary>
        internal static string QuyenTB_BANGIAO {
            get {
                return ResourceManager.GetString("QuyenTB_BANGIAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý chương trình mượn.
        /// </summary>
        internal static string QuyenTB_CHUONGTRINH {
            get {
                return ResourceManager.GetString("QuyenTB_CHUONGTRINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề xuất mua thiết bị.
        /// </summary>
        internal static string QuyenTB_DEXUAT {
            get {
                return ResourceManager.GetString("QuyenTB_DEXUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import dữ liệu cũ.
        /// </summary>
        internal static string QuyenTB_IMPORT {
            get {
                return ResourceManager.GetString("QuyenTB_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý key bản quyền.
        /// </summary>
        internal static string QuyenTB_KEYPM {
            get {
                return ResourceManager.GetString("QuyenTB_KEYPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm kê thiết bị.
        /// </summary>
        internal static string QuyenTB_KIEMKE {
            get {
                return ResourceManager.GetString("QuyenTB_KIEMKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký mượn.
        /// </summary>
        internal static string QuyenTB_MUON {
            get {
                return ResourceManager.GetString("QuyenTB_MUON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý mượn, trả thiết bị.
        /// </summary>
        internal static string QuyenTB_MUONTRA {
            get {
                return ResourceManager.GetString("QuyenTB_MUONTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị .
        /// </summary>
        internal static string QuyenTB_THIETBI {
            get {
                return ResourceManager.GetString("QuyenTB_THIETBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo không tồn tại.
        /// </summary>
        internal static string strBaoCaoKhongTonTai {
            get {
                return ResourceManager.GetString("strBaoCaoKhongTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng.
        /// </summary>
        internal static string strDangNhapSai {
            get {
                return ResourceManager.GetString("strDangNhapSai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //FileSign.
        /// </summary>
        internal static string strFolderSign {
            get {
                return ResourceManager.GetString("strFolderSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập chức năng này.
        /// </summary>
        internal static string strKhongCoQuyen {
            get {
                return ResourceManager.GetString("strKhongCoQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không có thông tin Email..
        /// </summary>
        internal static string strKhongEmail {
            get {
                return ResourceManager.GetString("strKhongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin không được hỗ trợ ký số.
        /// </summary>
        internal static string strKhongHoTroKySo {
            get {
                return ResourceManager.GetString("strKhongHoTroKySo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp tin không được hỗ trợ xem trên trình duyệt.
        /// </summary>
        internal static string strKhongHoTroXem {
            get {
                return ResourceManager.GetString("strKhongHoTroXem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lựa chọn thất bại!.
        /// </summary>
        internal static string strLuaChonSai {
            get {
                return ResourceManager.GetString("strLuaChonSai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuAdmin.
        /// </summary>
        internal static string strMenuAdmin {
            get {
                return ResourceManager.GetString("strMenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuUser.
        /// </summary>
        internal static string strMenuUser {
            get {
                return ResourceManager.GetString("strMenuUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã bị khoá do đăng nhập sai quá số lần cho phép.
        /// </summary>
        internal static string strQuaLanDangNhap {
            get {
                return ResourceManager.GetString("strQuaLanDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác nhận không đúng.
        /// </summary>
        internal static string strSaiMaXacNhan {
            get {
                return ResourceManager.GetString("strSaiMaXacNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không tồn tại.
        /// </summary>
        internal static string strSaiTenDangNhap {
            get {
                return ResourceManager.GetString("strSaiTenDangNhap", resourceCulture);
            }
        }
    }
}
